// Generated by https://quicktype.io

export interface ApiUser {
    id: number;
    name: string;
    status: string;
    species: string;
    type: string;
    gender: string;
    origin: UserAssosiatedUrl;
    location: UserAssosiatedUrl;
    image: string;
    episode: string[];
    url: string;
    created: string;
}

export interface User {
    id: number;
    name: string;
    status: string;
    species: string;
}

export interface UserAssosiatedUrl {
    name: string;
    url: string;
}

// const emptyUserAssosiatedUrl = {
//     name: '',
//     url: '',
// }

export const userEmptyState: User = {
    id: 0,
    name: '',
    status: '',
    species: '',
}


